### ISSUE TITLE
Generate missing GML thumbnails 

### ISSUE THREAD

**Issue by jamiew** [jamiew/blackbook#10]
> 50% of the tags on the site don't have thumbnails because DustTag doesn't upload them. We need something that can generate thumbnails for them, be it via ruby, php, SVG, javascript...

**Comment by tbx** [comment]
no idea how-to get dusttag running on a server though!? It's c++ I think!? I will ask Evan maybe later today if that's possible for Chris to implement into the next release. (He's back in Paris)
We should have a standard-style server-side "gml to image" generator though, because many apps will follow. -> Something to ask the 000000book community!? You got almost 700 followers on twitter!!! (We'll need to implement twitter into the website, too)

**Comment by jamiew** [comment]
Those are zombie followers ;)

We'll need something server-side... I emailed the GML mailing list yesterday, and the author of http://graffitar.com (which already has a GML PHP SVG renderer!) 

I've also made a canvasplayer which can dump a PNG, which could be uploaded via fallback (but that's not ideal since it requires someone to view it)

**Comment by jamiew** [comment]
This was closed a while ago using the cmdline python GML generator...
