### ISSUE TITLE
UUIDs, uniqueKeys, device pairing and user authentication

### ISSUE THREAD

**Issue by tbx** [jamiew/blackbook#14]
- your application should be able to include a 'uniqueKey' tag in its GML header that specifies an iPhone UUID, computer MAC address, etc. – something to uniquely identify the device for later pairing with a user account.
- This uniqueKey will be parsed, SHA-1 hashed & stripped from public display to maintain user privacy

**Comment by tbx** [comment]
Why don't we solve this with a "forced" user login instead of creating an uniqueKey?
(of course, anonymous uploading always is an option) 
hmm.... is that it just because user authentication currently doesn't work in the API + apps would need an interface for a user login in order to have their "personal stream?
(btw, getting a MAC address seems to me impossible with "web privileged" javascript anyways- I hope so!)

**Comment by jamiew** [comment]
Could use any kind of unique identifer for the browser, or even a codeword+version+IP hash, then display it back to the user in your app/addon. 

It's the most simple thing any app on any platform could do semi-securely... makes it a custom API key per-app, rather than requiring registration and asking for username/password (or OAauth, which is even more involved)

**Comment by jamiew** [comment]
This is an issue again because Apple is removing UUID access from devices... will need to support some kind of alternate login going forward
